"""empty message

Revision ID: 219ec2307653
Revises: 42de641eb7cc
Create Date: 2019-08-21 10:08:51.675869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219ec2307653'
down_revision = '42de641eb7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
